CREATE OR REPLACE VIEW `__DATASET__.vw_estoque_posicao` AS
SELECT
  COALESCE(g.__COL_GRUPO_NOME__, 'Sem grupo') AS grupo,
  COUNT(DISTINCT a.__COL_PROD_ID__) AS itens,
  SUM(`__DATASET__`.pm_num(a.__COL_SALDO__)) AS saldo
FROM `__DATASET__.EST_ALMOXARIFADO_PRODUTO` a
LEFT JOIN `__DATASET__.EST_PRODUTO` p ON CAST(p.__COL_PROD_PK__ AS STRING) = CAST(a.__COL_PROD_ID__ AS STRING)
LEFT JOIN `__DATASET__.EST_GRUPO` g ON CAST(g.__COL_GRUPO_PK__ AS STRING) = CAST(p.__COL_PROD_GRUPO__ AS STRING)
GROUP BY grupo ORDER BY saldo DESC;
